### PR TITLE
Amphp

### PR DESCRIPTION
**Pull request by acondura**

### CODE REVIEW

**Comment by w00fz** [comment]
Did you mean to create this PR?

**Comment by acondura** [comment]
Ouch, no, I didn't realize I did that. I thought it applies only to my
forked repo.

**Comment by rhukster** [comment]
If you don't plan on pushing your modifications back to the original `docker-grav` repo, you should close this pull request.

**Comment by acondura** [comment]
Right, it's more on the research side now. Thanks.

**Pull request closed without merging**
